name: Test fetching

on:
  push:
    branches:
      - master
    paths:
      - '**.rs'
  pull_request:
    branches:
      - master
    paths:
      - '**.rs'
  schedule:
    - cron: "0 2 * * 0,2,4"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Test fetching on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - nightly
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          default: true
      - name: Run test `two_video_descrambler_instances_of_same_video_are_eq`
        run: cargo test -p rustube --all-features --test fetch_descramble two_video_descrambler_instances_of_same_video_are_eq -- --exact --ignored
      - name: Run test `differently_constructed_videos_are_eq`
        run: cargo test -p rustube --all-features --test fetch_descramble differently_constructed_videos_are_eq -- --exact --ignored
